name-template: Micronaut AWS $NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: "type:"
  - title: 🐛 Bug Fixes
    label: "type: bug"
  - title: 🛠 Dependency upgrades
    label: "type: dependencies"
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
